server {

  location /featureserver/ {
    proxy_pass http://pg-feat-archeshedatatransformation:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-archeshedatatransformation:7800/tileserver/;
  }

  location / {
    proxy_pass http://archeshedatatransformation:8000/;
  }

}